[package]
name = "webtech"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
version = "0.3.3"
default-features = false
features = ["json"]